// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// User API 定义，包含用户信息、登录请求和响应等相关消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: apiserver/v1/app/user.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gender 表示用户性别
type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0 // 未设置
	Gender_GENDER_MALE        Gender = 1 // 男
	Gender_GENDER_FEMALE      Gender = 2 // 女
	Gender_GENDER_OTHER       Gender = 3 // 其他
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
		3: "GENDER_OTHER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
		"GENDER_OTHER":       3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_apiserver_v1_app_user_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_apiserver_v1_app_user_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{0}
}

// RegisterSource 表示用户注册来源
type RegisterSource int32

const (
	RegisterSource_REGISTER_SOURCE_UNSPECIFIED RegisterSource = 0 // 未指定
	RegisterSource_REGISTER_SOURCE_WEB         RegisterSource = 1 // Web
	RegisterSource_REGISTER_SOURCE_APP         RegisterSource = 2 // App
	RegisterSource_REGISTER_SOURCE_WECHAT      RegisterSource = 3 // 微信
	RegisterSource_REGISTER_SOURCE_QQ          RegisterSource = 4 // QQ
	RegisterSource_REGISTER_SOURCE_GITHUB      RegisterSource = 5 // GitHub
	RegisterSource_REGISTER_SOURCE_GOOGLE      RegisterSource = 6 // Google
)

// Enum value maps for RegisterSource.
var (
	RegisterSource_name = map[int32]string{
		0: "REGISTER_SOURCE_UNSPECIFIED",
		1: "REGISTER_SOURCE_WEB",
		2: "REGISTER_SOURCE_APP",
		3: "REGISTER_SOURCE_WECHAT",
		4: "REGISTER_SOURCE_QQ",
		5: "REGISTER_SOURCE_GITHUB",
		6: "REGISTER_SOURCE_GOOGLE",
	}
	RegisterSource_value = map[string]int32{
		"REGISTER_SOURCE_UNSPECIFIED": 0,
		"REGISTER_SOURCE_WEB":         1,
		"REGISTER_SOURCE_APP":         2,
		"REGISTER_SOURCE_WECHAT":      3,
		"REGISTER_SOURCE_QQ":          4,
		"REGISTER_SOURCE_GITHUB":      5,
		"REGISTER_SOURCE_GOOGLE":      6,
	}
)

func (x RegisterSource) Enum() *RegisterSource {
	p := new(RegisterSource)
	*p = x
	return p
}

func (x RegisterSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterSource) Descriptor() protoreflect.EnumDescriptor {
	return file_apiserver_v1_app_user_proto_enumTypes[1].Descriptor()
}

func (RegisterSource) Type() protoreflect.EnumType {
	return &file_apiserver_v1_app_user_proto_enumTypes[1]
}

func (x RegisterSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterSource.Descriptor instead.
func (RegisterSource) EnumDescriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{1}
}

// User 表示用户信息
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userID 表示用户 ID
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	// username 表示用户名称
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// age 表示用户年龄
	Age *int32 `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	// avatar 表示用户头像URL
	Avatar *string `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// email 表示用户电子邮箱
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// emailVerified 表示邮箱是否已验证
	EmailVerified bool `protobuf:"varint,6,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	// phone 表示用户手机号
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	// phoneVerified 表示手机号是否已验证
	PhoneVerified bool `protobuf:"varint,8,opt,name=phoneVerified,proto3" json:"phoneVerified,omitempty"`
	// gender 表示用户性别
	Gender Gender `protobuf:"varint,9,opt,name=gender,proto3,enum=v1.Gender" json:"gender,omitempty"`
	// status 表示用户状态：1-正常，0-禁用
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	// failedLoginAttempts 表示失败登录次数
	FailedLoginAttempts int32 `protobuf:"varint,11,opt,name=failedLoginAttempts,proto3" json:"failedLoginAttempts,omitempty"`
	// lastLoginAt 表示最后登录时间（Unix 时间戳）
	LastLoginAt *int64 `protobuf:"varint,12,opt,name=lastLoginAt,proto3,oneof" json:"lastLoginAt,omitempty"`
	// lastLoginIP 表示最后登录IP
	LastLoginIP *string `protobuf:"bytes,13,opt,name=lastLoginIP,proto3,oneof" json:"lastLoginIP,omitempty"`
	// lastLoginDevice 表示最后登录设备
	LastLoginDevice *string `protobuf:"bytes,14,opt,name=lastLoginDevice,proto3,oneof" json:"lastLoginDevice,omitempty"`
	// isRisk 表示是否为风险用户
	IsRisk bool `protobuf:"varint,15,opt,name=isRisk,proto3" json:"isRisk,omitempty"`
	// registerSource 表示注册来源
	RegisterSource RegisterSource `protobuf:"varint,16,opt,name=registerSource,proto3,enum=v1.RegisterSource" json:"registerSource,omitempty"`
	// registerIP 表示注册IP
	RegisterIP *string `protobuf:"bytes,17,opt,name=registerIP,proto3,oneof" json:"registerIP,omitempty"`
	// wechatOpenID 表示微信OpenID
	WechatOpenID *string `protobuf:"bytes,18,opt,name=wechatOpenID,proto3,oneof" json:"wechatOpenID,omitempty"`
	// passwordUpdatedAt 表示密码更新时间（Unix 时间戳）
	PasswordUpdatedAt *int64 `protobuf:"varint,19,opt,name=passwordUpdatedAt,proto3,oneof" json:"passwordUpdatedAt,omitempty"`
	// createdAt 表示用户注册时间（Unix 时间戳）
	CreatedAt int64 `protobuf:"varint,20,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示用户最后更新时间（Unix 时间戳）
	UpdatedAt     int64 `protobuf:"varint,21,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *User) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetFailedLoginAttempts() int32 {
	if x != nil {
		return x.FailedLoginAttempts
	}
	return 0
}

func (x *User) GetLastLoginAt() int64 {
	if x != nil && x.LastLoginAt != nil {
		return *x.LastLoginAt
	}
	return 0
}

func (x *User) GetLastLoginIP() string {
	if x != nil && x.LastLoginIP != nil {
		return *x.LastLoginIP
	}
	return ""
}

func (x *User) GetLastLoginDevice() string {
	if x != nil && x.LastLoginDevice != nil {
		return *x.LastLoginDevice
	}
	return ""
}

func (x *User) GetIsRisk() bool {
	if x != nil {
		return x.IsRisk
	}
	return false
}

func (x *User) GetRegisterSource() RegisterSource {
	if x != nil {
		return x.RegisterSource
	}
	return RegisterSource_REGISTER_SOURCE_UNSPECIFIED
}

func (x *User) GetRegisterIP() string {
	if x != nil && x.RegisterIP != nil {
		return *x.RegisterIP
	}
	return ""
}

func (x *User) GetWechatOpenID() string {
	if x != nil && x.WechatOpenID != nil {
		return *x.WechatOpenID
	}
	return ""
}

func (x *User) GetPasswordUpdatedAt() int64 {
	if x != nil && x.PasswordUpdatedAt != nil {
		return *x.PasswordUpdatedAt
	}
	return 0
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// LoginRequest 表示登录请求
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username 表示用户名称
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password 表示用户密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse 表示登录响应
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token 表示返回的身份验证令牌
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// expireAt 表示该 token 的过期时间（Unix 时间戳）
	ExpireAt      int64 `protobuf:"varint,2,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// RefreshTokenRequest 表示刷新令牌的请求
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{3}
}

// RefreshTokenResponse 表示刷新令牌的响应
type RefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token 表示返回的身份验证令牌
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// expireAt 表示该 token 的过期时间（Unix 时间戳）
	ExpireAt      int64 `protobuf:"varint,2,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// ChangePasswordRequest 表示修改密码请求
type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userID 表示用户 ID
	// @gotags: uri:"userID"
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" uri:"userID"`
	// oldPassword 表示当前密码
	OldPassword string `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	// newPassword 表示准备修改的新密码
	NewPassword   string `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordResponse 表示修改密码响应
type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{6}
}

// CreateUserRequest 表示创建用户请求
type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// username 表示用户名称
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// password 表示用户密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// age 表示用户年龄
	Age *int32 `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	// avatar 表示用户头像URL
	Avatar *string `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// email 表示用户电子邮箱
	Email string `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	// phone 表示用户手机号
	Phone *string `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	// gender 表示用户性别
	Gender *Gender `protobuf:"varint,7,opt,name=gender,proto3,enum=v1.Gender,oneof" json:"gender,omitempty"`
	// registerSource 表示注册来源
	RegisterSource RegisterSource `protobuf:"varint,8,opt,name=registerSource,proto3,enum=v1.RegisterSource" json:"registerSource,omitempty"`
	// registerIP 表示注册IP
	RegisterIP *string `protobuf:"bytes,9,opt,name=registerIP,proto3,oneof" json:"registerIP,omitempty"`
	// wechatOpenID 表示微信OpenID
	WechatOpenID  *string `protobuf:"bytes,10,opt,name=wechatOpenID,proto3,oneof" json:"wechatOpenID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetGender() Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *CreateUserRequest) GetRegisterSource() RegisterSource {
	if x != nil {
		return x.RegisterSource
	}
	return RegisterSource_REGISTER_SOURCE_UNSPECIFIED
}

func (x *CreateUserRequest) GetRegisterIP() string {
	if x != nil && x.RegisterIP != nil {
		return *x.RegisterIP
	}
	return ""
}

func (x *CreateUserRequest) GetWechatOpenID() string {
	if x != nil && x.WechatOpenID != nil {
		return *x.WechatOpenID
	}
	return ""
}

// CreateUserResponse 表示创建用户响应
type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userID 表示新创建的用户 ID
	UserID        string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserResponse) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// UpdateUserRequest 表示更新用户请求
type UpdateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userID 表示用户 ID
	// @gotags: uri:"userID"
	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" uri:"userID"`
	// username 表示可选的用户名称
	Username *string `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// age 表示可选的用户年龄
	Age *int32 `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	// avatar 表示可选的用户头像URL
	Avatar *string `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// email 表示可选的用户电子邮箱
	Email *string `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// phone 表示可选的用户手机号
	Phone *string `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	// gender 表示可选的用户性别
	Gender *Gender `protobuf:"varint,7,opt,name=gender,proto3,enum=v1.Gender,oneof" json:"gender,omitempty"`
	// status 表示可选的用户状态
	Status *int32 `protobuf:"varint,8,opt,name=status,proto3,oneof" json:"status,omitempty"`
	// isRisk 表示可选的用户风险状态
	IsRisk        *bool `protobuf:"varint,9,opt,name=isRisk,proto3,oneof" json:"isRisk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetGender() Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *UpdateUserRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *UpdateUserRequest) GetIsRisk() bool {
	if x != nil && x.IsRisk != nil {
		return *x.IsRisk
	}
	return false
}

// UpdateUserResponse 表示更新用户响应
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{10}
}

// DeleteUserRequest 表示删除用户请求
type DeleteUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userID 表示用户 ID
	// @gotags: uri:"userID"
	UserID        string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" uri:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// DeleteUserResponse 表示删除用户响应
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{12}
}

// GetUserRequest 表示获取用户请求
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// userID 表示用户 ID
	// @gotags: uri:"userID"
	UserID        string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" uri:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// GetUserResponse 表示获取用户响应
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user 表示返回的用户信息
	User          *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// ListUserRequest 表示获取用户列表请求
type ListUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示分页偏移量
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// limit 表示每页数量
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{15}
}

func (x *ListUserRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListUserRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListUserResponse 表示获取用户列表响应
type ListUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// totalCount 表示用户总数
	TotalCount int64 `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	// users 表示用户列表
	Users         []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_apiserver_v1_app_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_app_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_app_user_proto_rawDescGZIP(), []int{16}
}

func (x *ListUserResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_apiserver_v1_app_user_proto protoreflect.FileDescriptor

const file_apiserver_v1_app_user_proto_rawDesc = "" +
	"\n" +
	"\x1bapiserver/v1/app/user.proto\x12\x02v1\"\xdf\x06\n" +
	"\x04User\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x15\n" +
	"\x03age\x18\x03 \x01(\x05H\x00R\x03age\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x04 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12$\n" +
	"\remailVerified\x18\x06 \x01(\bR\remailVerified\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12$\n" +
	"\rphoneVerified\x18\b \x01(\bR\rphoneVerified\x12\"\n" +
	"\x06gender\x18\t \x01(\x0e2\n" +
	".v1.GenderR\x06gender\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x120\n" +
	"\x13failedLoginAttempts\x18\v \x01(\x05R\x13failedLoginAttempts\x12%\n" +
	"\vlastLoginAt\x18\f \x01(\x03H\x02R\vlastLoginAt\x88\x01\x01\x12%\n" +
	"\vlastLoginIP\x18\r \x01(\tH\x03R\vlastLoginIP\x88\x01\x01\x12-\n" +
	"\x0flastLoginDevice\x18\x0e \x01(\tH\x04R\x0flastLoginDevice\x88\x01\x01\x12\x16\n" +
	"\x06isRisk\x18\x0f \x01(\bR\x06isRisk\x12:\n" +
	"\x0eregisterSource\x18\x10 \x01(\x0e2\x12.v1.RegisterSourceR\x0eregisterSource\x12#\n" +
	"\n" +
	"registerIP\x18\x11 \x01(\tH\x05R\n" +
	"registerIP\x88\x01\x01\x12'\n" +
	"\fwechatOpenID\x18\x12 \x01(\tH\x06R\fwechatOpenID\x88\x01\x01\x121\n" +
	"\x11passwordUpdatedAt\x18\x13 \x01(\x03H\aR\x11passwordUpdatedAt\x88\x01\x01\x12\x1c\n" +
	"\tcreatedAt\x18\x14 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x15 \x01(\x03R\tupdatedAtB\x06\n" +
	"\x04_ageB\t\n" +
	"\a_avatarB\x0e\n" +
	"\f_lastLoginAtB\x0e\n" +
	"\f_lastLoginIPB\x12\n" +
	"\x10_lastLoginDeviceB\r\n" +
	"\v_registerIPB\x0f\n" +
	"\r_wechatOpenIDB\x14\n" +
	"\x12_passwordUpdatedAt\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bexpireAt\x18\x02 \x01(\x03R\bexpireAt\"\x15\n" +
	"\x13RefreshTokenRequest\"H\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bexpireAt\x18\x02 \x01(\x03R\bexpireAt\"s\n" +
	"\x15ChangePasswordRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12 \n" +
	"\voldPassword\x18\x02 \x01(\tR\voldPassword\x12 \n" +
	"\vnewPassword\x18\x03 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16ChangePasswordResponse\"\xab\x03\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x15\n" +
	"\x03age\x18\x03 \x01(\x05H\x00R\x03age\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x04 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x02R\x05phone\x88\x01\x01\x12'\n" +
	"\x06gender\x18\a \x01(\x0e2\n" +
	".v1.GenderH\x03R\x06gender\x88\x01\x01\x12:\n" +
	"\x0eregisterSource\x18\b \x01(\x0e2\x12.v1.RegisterSourceR\x0eregisterSource\x12#\n" +
	"\n" +
	"registerIP\x18\t \x01(\tH\x04R\n" +
	"registerIP\x88\x01\x01\x12'\n" +
	"\fwechatOpenID\x18\n" +
	" \x01(\tH\x05R\fwechatOpenID\x88\x01\x01B\x06\n" +
	"\x04_ageB\t\n" +
	"\a_avatarB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_genderB\r\n" +
	"\v_registerIPB\x0f\n" +
	"\r_wechatOpenID\",\n" +
	"\x12CreateUserResponse\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"\xee\x02\n" +
	"\x11UpdateUserRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x03 \x01(\x05H\x01R\x03age\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x04 \x01(\tH\x02R\x06avatar\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x03R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x04R\x05phone\x88\x01\x01\x12'\n" +
	"\x06gender\x18\a \x01(\x0e2\n" +
	".v1.GenderH\x05R\x06gender\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\x05H\x06R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06isRisk\x18\t \x01(\bH\aR\x06isRisk\x88\x01\x01B\v\n" +
	"\t_usernameB\x06\n" +
	"\x04_ageB\t\n" +
	"\a_avatarB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_genderB\t\n" +
	"\a_statusB\t\n" +
	"\a_isRisk\"\x14\n" +
	"\x12UpdateUserResponse\"+\n" +
	"\x11DeleteUserRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"\x14\n" +
	"\x12DeleteUserResponse\"(\n" +
	"\x0eGetUserRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"/\n" +
	"\x0fGetUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.v1.UserR\x04user\"?\n" +
	"\x0fListUserRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"R\n" +
	"\x10ListUserResponse\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x01 \x01(\x03R\n" +
	"totalCount\x12\x1e\n" +
	"\x05users\x18\x02 \x03(\v2\b.v1.UserR\x05users*V\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02\x12\x10\n" +
	"\fGENDER_OTHER\x10\x03*\xcf\x01\n" +
	"\x0eRegisterSource\x12\x1f\n" +
	"\x1bREGISTER_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13REGISTER_SOURCE_WEB\x10\x01\x12\x17\n" +
	"\x13REGISTER_SOURCE_APP\x10\x02\x12\x1a\n" +
	"\x16REGISTER_SOURCE_WECHAT\x10\x03\x12\x16\n" +
	"\x12REGISTER_SOURCE_QQ\x10\x04\x12\x1a\n" +
	"\x16REGISTER_SOURCE_GITHUB\x10\x05\x12\x1a\n" +
	"\x16REGISTER_SOURCE_GOOGLE\x10\x06B<Z:github.com/clin211/miniblog-v2/pkg/api/apiserver/v1/app;v1b\x06proto3"

var (
	file_apiserver_v1_app_user_proto_rawDescOnce sync.Once
	file_apiserver_v1_app_user_proto_rawDescData []byte
)

func file_apiserver_v1_app_user_proto_rawDescGZIP() []byte {
	file_apiserver_v1_app_user_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_app_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_app_user_proto_rawDesc), len(file_apiserver_v1_app_user_proto_rawDesc)))
	})
	return file_apiserver_v1_app_user_proto_rawDescData
}

var file_apiserver_v1_app_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_apiserver_v1_app_user_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_apiserver_v1_app_user_proto_goTypes = []any{
	(Gender)(0),                    // 0: v1.Gender
	(RegisterSource)(0),            // 1: v1.RegisterSource
	(*User)(nil),                   // 2: v1.User
	(*LoginRequest)(nil),           // 3: v1.LoginRequest
	(*LoginResponse)(nil),          // 4: v1.LoginResponse
	(*RefreshTokenRequest)(nil),    // 5: v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 6: v1.RefreshTokenResponse
	(*ChangePasswordRequest)(nil),  // 7: v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 8: v1.ChangePasswordResponse
	(*CreateUserRequest)(nil),      // 9: v1.CreateUserRequest
	(*CreateUserResponse)(nil),     // 10: v1.CreateUserResponse
	(*UpdateUserRequest)(nil),      // 11: v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 12: v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),      // 13: v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 14: v1.DeleteUserResponse
	(*GetUserRequest)(nil),         // 15: v1.GetUserRequest
	(*GetUserResponse)(nil),        // 16: v1.GetUserResponse
	(*ListUserRequest)(nil),        // 17: v1.ListUserRequest
	(*ListUserResponse)(nil),       // 18: v1.ListUserResponse
}
var file_apiserver_v1_app_user_proto_depIdxs = []int32{
	0, // 0: v1.User.gender:type_name -> v1.Gender
	1, // 1: v1.User.registerSource:type_name -> v1.RegisterSource
	0, // 2: v1.CreateUserRequest.gender:type_name -> v1.Gender
	1, // 3: v1.CreateUserRequest.registerSource:type_name -> v1.RegisterSource
	0, // 4: v1.UpdateUserRequest.gender:type_name -> v1.Gender
	2, // 5: v1.GetUserResponse.user:type_name -> v1.User
	2, // 6: v1.ListUserResponse.users:type_name -> v1.User
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_apiserver_v1_app_user_proto_init() }
func file_apiserver_v1_app_user_proto_init() {
	if File_apiserver_v1_app_user_proto != nil {
		return
	}
	file_apiserver_v1_app_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_apiserver_v1_app_user_proto_msgTypes[7].OneofWrappers = []any{}
	file_apiserver_v1_app_user_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_app_user_proto_rawDesc), len(file_apiserver_v1_app_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_app_user_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_app_user_proto_depIdxs,
		EnumInfos:         file_apiserver_v1_app_user_proto_enumTypes,
		MessageInfos:      file_apiserver_v1_app_user_proto_msgTypes,
	}.Build()
	File_apiserver_v1_app_user_proto = out.File
	file_apiserver_v1_app_user_proto_goTypes = nil
	file_apiserver_v1_app_user_proto_depIdxs = nil
}
