version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: miniblog-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: miniblog
      MYSQL_PASSWORD: CueD7wbmJHxY
      MYSQL_DATABASE: miniblog
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local
