# Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/clin211/miniblog-v2.git.

# 服务器类型，可选值有：
#   grpc：启动一个 gRPC 服务器
#   grpc-gateway: 启动一个 gRPC 服务器 + HTTP 反向代理服务器
#   gin：基于 gin 框架启动一个 HTTP 服务器
# 服务器模式选择：
#   - 应用内调用选择 grpc
#   - 如果有外部服务调用选择 grpc-gateway
#   - 学习 Gin 框架时选择 gin
server-mode: gin

# GRPC 服务器相关配置
grpc:
  # GRPC 服务器监听地址
  addr: :6666

# HTTP 服务器相关配置
http:
  # HTTP 服务器监听地址
  addr: :5555

# 安全服务器相关配置
tls:
  # 是否启动 HTTPS 安全服务器
  # 生产环境建议开启 HTTPS。并使用 HTTPS 协议访问 API 接口
  use-tls: false
  # 证书
  cert: ./cert/server.crt
  # 证书 Key 文件
  key: ./cert/server.key

# JWT 签发密钥
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

# MySQL 数据库相关配置
mysql:
  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  addr: 127.0.0.1:11006
  # MySQL 用户名(建议授权最小权限集)
  username: root
  # MySQL 用户密码
  password: 123456
  # miniblog 系统所用的数据库名
  database: miniblog_v2
  # 数据库字符集
  charset: utf8mb4
  # MySQL 最大空闲连接数，默认 100
  max-idle-connections: 100
  # MySQL 最大打开的连接数，默认 100
  max-open-connections: 100
  # 空闲连接最大存活时间，默认 10s
  max-connection-life-time: 10s
  # GORM 日志级别, 1: silent, 2:error, 3:warn, 4:info
  # 生产环境建议设置为 4
  log-level: 4

# mongoDB 相关配置
mongo:
  # mongoDB 链接方式，使用 root 用户和 admin 认证数据库
  url: mongodb://root:r8SggC783Xh1@127.0.0.1:27001/miniblog_v2?directConnection=true&authSource=admin
  # MongoDB 数据库名
  database: miniblog_v2
  # MongoDB 集合名（可选，通常在代码中指定）
  collection: "device"
  # MongoDB 用户名（留空，因为认证信息在 URL 中）
  username: ""
  # MongoDB 用户密码（留空，因为认证信息在 URL 中）
  password: ""
  # 连接超时时间，默认 10s
  timeout: 10s

# Redis 数据库相关配置
redis:
  # Redis 服务器地址和端口，默认 127.0.0.1:6379
  addr: 127.0.0.1:63790
  # Redis 用户名（使用默认用户，留空）
  username: ""
  # Redis 用户密码
  password: v6yJM2kAZpOc
  # Redis 数据库索引，默认 0
  database: 0
  # 最大重试次数，默认 3
  max-retries: 3
  # 最小空闲连接数，默认 0
  min-idle-conns: 0
  # 拨号超时时间，默认 5s
  dial-timeout: 5s
  # 读取超时时间，默认 3s
  read-timeout: 3s
  # 写入超时时间，默认 3s
  write-timeout: 3s
  # 连接池超时时间，默认 4s
  pool-time: 4s
  # 连接池大小，默认 10
  pool-size: 10
  # 是否启用链路追踪，默认 false
  enable-trace: false

# 文件上传相关配置
upload:
  # 存储提供商：local / alioss（当前仅实现 local）
  provider: local
  # 最大上传大小
  maxSize: "20MB"
  # 允许的 MIME 类型
  allowedMIMEs: [ "image/jpeg", "image/png", "image/gif", "image/heic", "image/heif", "application/pdf" ]
  # 是否去重（按内容哈希）
  deduplicate: true
  # 对象键模板：{date:...} {sha256:N} {ext}
  keyTemplate: "{date:2006/01/02}/{sha256:16}{ext}"
  # 本地存储配置
  local:
    # 本地文件根目录（服务会自动创建）
    baseDir: "./_output/uploads"
    # 静态访问前缀路径（环境无关），例如 /static/uploads
    basePath: "/static/uploads"
    # 对外可访问完整前缀（含协议/域名/路径），不同环境请分别配置：
    #   开发示例:   http://localhost:5555/static/uploads
    #   测试示例:   https://api.test.example.com/static/uploads
    #   生产示例:   https://cdn.example.com/uploads
    # 若留空将回退为 basePath，仅返回路径，由同源网关提供访问
    baseURL: "http://localhost:5555/static/uploads"
    # 目录权限（十进制 493 = 八进制 0755）
    mkdirPerm: 493
  # 阿里云 OSS（占位，后续实现）
  alioss:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    bucket: "your-bucket-name"
    accessKeyID: "your-ak"
    accessKeySecret: "your-sk"
    securityToken: ""
    acl: "private"
    pathStyleAccess: false
    uploadTimeout: "30s"
    callbackURL: ""
  # 分片上传（预留，当前仅本地实现）
  multipart:
    enabled: true
    minSize: "8MB"
    maxParts: 10000
    partSize:
      min: "5MB"
      max: "128MB"
      default: "8MB"
    concurrencyLimitPerUser: 2
    uploadIdTTL: "24h"
    tempDir: "./_output/uploads/.multipart"
    checksum: "sha256"
    presign:
      enabled: true
      expires: "15m"
      mode: "direct"

# 日志配置
log:
  # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-caller: false
  # 是否禁止在 panic 及以上级别打印堆栈信息
  disable-stacktrace: false
  # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  # 生产环境建议设置为 info
  level: debug
  # 指定日志显示格式，可选值：console, json
  # 生产环境建议设置为 json
  format: json
  # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出
  output-paths: [ ./_output/miniblog.log, stdout ]
