# Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
# Use of this source code is governed by a MIT style
# license that can be found in the LICENSE file. The original repo for
# this file is https://github.com/clin211/miniblog-v2.git.

# 服务器类型，可选值有：
#   grpc：启动一个 gRPC 服务器
#   grpc-gateway: 启动一个 gRPC 服务器 + HTTP 反向代理服务器
#   gin：基于 gin 框架启动一个 HTTP 服务器
# 服务器模式选择：
#   - 应用内调用选择 grpc
#   - 如果有外部服务调用选择 grpc-gateway
#   - 学习 Gin 框架时选择 gin
server-mode: gin

# GRPC 服务器相关配置
grpc:
  # GRPC 服务器监听地址
  addr: :6666

# HTTP 服务器相关配置
http:
  # HTTP 服务器监听地址
  addr: :5555

# 安全服务器相关配置
tls:
  # 是否启动 HTTPS 安全服务器
  # 生产环境建议开启 HTTPS。并使用 HTTPS 协议访问 API 接口
  use-tls: false
  # 证书
  cert: ./cert/server.crt
  # 证书 Key 文件
  key: ./cert/server.key

# JWT 签发密钥
jwt-key: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

# MySQL 数据库相关配置
mysql:
  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  addr: 127.0.0.1:11006
  # MySQL 用户名(建议授权最小权限集)
  username: root
  # MySQL 用户密码
  password: 123456
  # miniblog 系统所用的数据库名
  database: miniblog_v2
  # MySQL 最大空闲连接数，默认 100
  max-idle-connections: 100
  # MySQL 最大打开的连接数，默认 100
  max-open-connections: 100
  # 空闲连接最大存活时间，默认 10s
  max-connection-life-time: 10s
  # GORM 日志级别, 1: silent, 2:error, 3:warn, 4:info
  # 生产环境建议设置为 4
  log-level: 4

# mongoDB 相关配置
mongo:
  # mongoDB 链接方式，添加authSource=admin解决认证问题
  url: mongodb://root:r8SggC783Xh1@127.0.0.1:27001/miniblog_v2?directConnection=true
  # MongoDB 数据库名
  database: miniblog_v2
  # MongoDB 集合名（可选，通常在代码中指定）
  collection: "device"
  # MongoDB 用户名
  username: root
  # MongoDB 用户密码
  password: r8SggC783Xh1
  # 连接超时时间，默认 10s
  timeout: 10s

# 日志配置
log:
  # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-caller: false
  # 是否禁止在 panic 及以上级别打印堆栈信息
  disable-stacktrace: false
  # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  # 生产环境建议设置为 info
  level: debug
  # 指定日志显示格式，可选值：console, json
  # 生产环境建议设置为 json
  format: json
  # 指定日志输出位置，多个输出，用 `逗号 + 空格` 分开。stdout：标准输出
  output-paths: [ ./_output/miniblog.log, stdout ]
