// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostM = "post"

// PostM 文章表
type PostM struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                // 主键
	PostID              string         `gorm:"column:post_id;not null;uniqueIndex:uk_post_id;comment:文章ID" json:"post_id"`                  // 文章ID
	Title               string         `gorm:"column:title;not null;comment:文章标题" json:"title"`                                             // 文章标题
	Content             *string        `gorm:"column:content;comment:文章内容" json:"content"`                                                  // 文章内容
	Cover               *string        `gorm:"column:cover;comment:文章封面" json:"cover"`                                                      // 文章封面
	Summary             *string        `gorm:"column:summary;comment:文章摘要" json:"summary"`                                                  // 文章摘要
	UserID              string         `gorm:"column:user_id;not null;index:idx_user_id;comment:用户ID（发布者用户ID）" json:"user_id"`              // 用户ID（发布者用户ID）
	CategoryID          *int32         `gorm:"column:category_id;index:idx_category_id;comment:分类ID" json:"category_id"`                    // 分类ID
	PostType            *int32         `gorm:"column:post_type;index:idx_post_type;default:1;comment:文章类型：1-原创，2-转载，3-投稿" json:"post_type"` // 文章类型：1-原创，2-转载，3-投稿
	OriginalAuthor      *string        `gorm:"column:original_author;comment:原作者姓名（转载时/投稿时使用）" json:"original_author"`                      // 原作者姓名（转载时/投稿时使用）
	OriginalSource      *string        `gorm:"column:original_source;comment:原文链接或来源（转载时/投稿时使用）" json:"original_source"`                    // 原文链接或来源（转载时/投稿时使用）
	OriginalAuthorIntro *string        `gorm:"column:original_author_intro;comment:原作者简介（转载时/投稿时使用）" json:"original_author_intro"`          // 原作者简介（转载时/投稿时使用）
	Position            *int32         `gorm:"column:position;comment:文章排序，0-默认排序，1-置顶，数字越大越靠前" json:"position"`                            // 文章排序，0-默认排序，1-置顶，数字越大越靠前
	ViewCount           *int32         `gorm:"column:view_count;comment:阅读次数" json:"view_count"`                                            // 阅读次数
	LikeCount           *int32         `gorm:"column:like_count;comment:点赞数" json:"like_count"`                                             // 点赞数
	Status              *int32         `gorm:"column:status;index:idx_status;default:1;comment:文章状态：1-草稿，2-已发布，3-已归档" json:"status"`        // 文章状态：1-草稿，2-已发布，3-已归档
	PublishedAt         *time.Time     `gorm:"column:published_at;comment:发布时间" json:"published_at"`                                        // 发布时间
	CreatedAt           *time.Time     `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt           *time.Time     `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updated_at"`                  // 更新时间
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;index:idx_deleted_at;comment:删除时间" json:"deleted_at"`                       // 删除时间
}

// TableName PostM's table name
func (*PostM) TableName() string {
	return TableNamePostM
}
