// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostTagM = "post_tag"

// PostTagM 文章标签关联表
type PostTagM struct {
	PostID    string         `gorm:"column:post_id;primaryKey:true;index:idx_post_id;comment:文章ID" json:"post_id"` // 文章ID
	TagID     int32          `gorm:"column:tag_id;primaryKey:true;index:idx_tag_id;comment:标签ID" json:"tag_id"`    // 标签ID
	CreatedAt *time.Time     `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updated_at"`   // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                             // 删除时间
}

// TableName PostTagM's table name
func (*PostTagM) TableName() string {
	return TableNamePostTagM
}
