// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePostM = "post"

// PostM mapped from table <post>
type PostM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:userID;not null;comment: ID" json:"userID"`                             //  ID
	PostID    string    `gorm:"column:postID;not null;uniqueIndex:idx_post_postID;comment: ID" json:"postID"` //  ID
	Title     string    `gorm:"column:title;not null" json:"title"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:current_timestamp" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:current_timestamp" json:"updatedAt"`
}

// TableName PostM's table name
func (*PostM) TableName() string {
	return TableNamePostM
}
