// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTagM = "tag"

// TagM 标签表
type TagM struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:标签ID" json:"id"`             // 标签ID
	Name      string         `gorm:"column:name;not null;uniqueIndex:uk_tag_name;comment:标签名称" json:"name"`      // 标签名称
	Color     *string        `gorm:"column:color;default:#007bff;comment:标签颜色(hex 格式)" json:"color"`             // 标签颜色(hex 格式)
	CreatedAt *time.Time     `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                           // 删除时间
}

// TableName TagM's table name
func (*TagM) TableName() string {
	return TableNameTagM
}
