// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserM = "user"

// UserM mapped from table <user>
type UserM struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID    string    `gorm:"column:userID;not null;uniqueIndex:idx_user_userID;comment: ID" json:"userID"` //  ID
	Username  string    `gorm:"column:username;not null;uniqueIndex:idx_user_username" json:"username"`
	Password  string    `gorm:"column:password;not null" json:"password"`
	Nickname  string    `gorm:"column:nickname;not null" json:"nickname"`
	Email     string    `gorm:"column:email;not null" json:"email"`
	Phone     string    `gorm:"column:phone;not null;uniqueIndex:idx_user_phone" json:"phone"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:current_timestamp" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null;default:current_timestamp" json:"updatedAt"`
}

// TableName UserM's table name
func (*UserM) TableName() string {
	return TableNameUserM
}
