// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserM = "user"

// UserM 用户表
type UserM struct {
	ID                  int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                                                   // 用户ID
	UserID              string         `gorm:"column:user_id;not null;uniqueIndex:uk_user_id;comment:用户ID" json:"user_id"`                                       // 用户ID
	Age                 *int32         `gorm:"column:age;comment:年龄" json:"age"`                                                                                 // 年龄
	Avatar              *string        `gorm:"column:avatar;comment:头像URL" json:"avatar"`                                                                        // 头像URL
	Username            string         `gorm:"column:username;not null;uniqueIndex:uk_username;comment:用户名" json:"username"`                                     // 用户名
	Password            string         `gorm:"column:password;not null;comment:密码" json:"password"`                                                              // 密码
	PasswordUpdatedAt   *time.Time     `gorm:"column:password_updated_at;comment:密码更新时间" json:"password_updated_at"`                                             // 密码更新时间
	Email               string         `gorm:"column:email;not null;uniqueIndex:uk_email;comment:邮箱" json:"email"`                                               // 邮箱
	EmailVerified       *int32         `gorm:"column:email_verified;comment:邮箱是否已验证；1-已验证,0-未验证" json:"email_verified"`                                          // 邮箱是否已验证；1-已验证,0-未验证
	Phone               string         `gorm:"column:phone;not null;uniqueIndex:uk_phone;comment:手机号" json:"phone"`                                              // 手机号
	PhoneVerified       *int32         `gorm:"column:phone_verified;comment:手机号是否已验证；1-已验证,0-未验证" json:"phone_verified"`                                         // 手机号是否已验证；1-已验证,0-未验证
	Gender              *int32         `gorm:"column:gender;comment:性别：0-未设置，1-男，2-女，3-其他" json:"gender"`                                                        // 性别：0-未设置，1-男，2-女，3-其他
	Status              *int32         `gorm:"column:status;index:idx_status;default:1;comment:状态：1-正常，0-禁用" json:"status"`                                      // 状态：1-正常，0-禁用
	FailedLoginAttempts *int32         `gorm:"column:failed_login_attempts;comment:失败登录次数，超过5次则锁定账户，登录成功后重置" json:"failed_login_attempts"`                       // 失败登录次数，超过5次则锁定账户，登录成功后重置
	LastLoginAt         *time.Time     `gorm:"column:last_login_at;comment:最后登录时间" json:"last_login_at"`                                                         // 最后登录时间
	LastLoginIP         *string        `gorm:"column:last_login_ip;comment:最后登录IP" json:"last_login_ip"`                                                         // 最后登录IP
	LastLoginDevice     *string        `gorm:"column:last_login_device;comment:最后登录设备" json:"last_login_device"`                                                 // 最后登录设备
	IsRisk              *int32         `gorm:"column:is_risk;comment:是否为风险用户；1-是,0-否" json:"is_risk"`                                                            // 是否为风险用户；1-是,0-否
	RegisterSource      *int32         `gorm:"column:register_source;default:1;comment:注册来源：1-web，2-app，3-wechat，4-qq，5-github，6-google" json:"register_source"` // 注册来源：1-web，2-app，3-wechat，4-qq，5-github，6-google
	RegisterIP          *string        `gorm:"column:register_ip;comment:注册IP" json:"register_ip"`                                                               // 注册IP
	WechatOpenID        *string        `gorm:"column:wechat_openid;uniqueIndex:uk_wechat_openid;comment:微信OpenID" json:"wechat_openid"`                          // 微信OpenID
	CreatedAt           *time.Time     `gorm:"column:created_at;default:current_timestamp;comment:创建时间" json:"created_at"`                                       // 创建时间
	UpdatedAt           *time.Time     `gorm:"column:updated_at;default:current_timestamp;comment:更新时间" json:"updated_at"`                                       // 更新时间
	DeletedAt           gorm.DeletedAt `gorm:"column:deleted_at;index:idx_deleted_at;comment:删除时间" json:"deleted_at"`                                            // 删除时间
}

// TableName UserM's table name
func (*UserM) TableName() string {
	return TableNameUserM
}
