// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: apiserver/v1/apiserver.proto

package v1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apiserver_v1_apiserver_proto protoreflect.FileDescriptor

const file_apiserver_v1_apiserver_proto_rawDesc = "" +
	"\n" +
	"\x1capiserver/v1/apiserver.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1aapiserver/v1/healthz.proto\x1a\x17apiserver/v1/post.proto\x1a\x17apiserver/v1/user.proto\x1a\x1bapiserver/v1/category.proto\x1a\x16apiserver/v1/tag.proto\x1a\x1bapiserver/v1/post_tag.proto\x1a\x1eapiserver/v1/upload_file.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xcb2\n" +
	"\bMiniBlog\x12v\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x13.v1.HealthzResponse\">\x92A+\n" +
	"\f服务治理\x12\x12服务健康检查*\aHealthz\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/healthz\x12\x8f\x01\n" +
	"\n" +
	"UploadFile\x12\x15.v1.UploadFileRequest\x1a\x12.v1.UploadedObject\"V\x92A2\n" +
	"\x13system/文件上传\x12\x0f单文件上传*\n" +
	"UploadFile\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/system/upload/file\x12\xaf\x01\n" +
	"\rInitMultipart\x12\x18.v1.InitMultipartRequest\x1a\x19.v1.InitMultipartResponse\"i\x92A;\n" +
	"\x13system/文件上传\x12\x15初始化分片上传*\rInitMultipart\x82\xd3\xe4\x93\x02%:\x01*\" /v1/system/upload/multipart/init\x12\xbe\x01\n" +
	"\fPresignParts\x12\x17.v1.PresignPartsRequest\x1a\x18.v1.PresignPartsResponse\"{\x92AJ\n" +
	"\x13system/文件上传\x12%批量获取直传分片预签名 URL*\fPresignParts\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/system/upload/multipart/presign\x12\xa6\x01\n" +
	"\n" +
	"UploadPart\x12\x15.v1.UploadPartRequest\x1a\x16.v1.UploadPartResponse\"i\x92A;\n" +
	"\x13system/文件上传\x12\x18代理上传单个分片*\n" +
	"UploadPart\x82\xd3\xe4\x93\x02%:\x01*\x1a /v1/system/upload/multipart/part\x12\xa8\x01\n" +
	"\tListParts\x12\x14.v1.ListPartsRequest\x1a\x15.v1.ListPartsResponse\"n\x92A7\n" +
	"\x13system/文件上传\x12\x15查询已上传分片*\tListParts\x82\xd3\xe4\x93\x02.\x12,/v1/system/upload/multipart/{uploadID}/parts\x12\xc0\x01\n" +
	"\x11CompleteMultipart\x12\x1c.v1.CompleteMultipartRequest\x1a\x1d.v1.CompleteMultipartResponse\"n\x92A<\n" +
	"\x13system/文件上传\x12\x12完成分片上传*\x11CompleteMultipart\x82\xd3\xe4\x93\x02):\x01*\"$/v1/system/upload/multipart/complete\x12\xb1\x01\n" +
	"\x0eAbortMultipart\x12\x19.v1.AbortMultipartRequest\x1a\x1a.v1.AbortMultipartResponse\"h\x92A9\n" +
	"\x13system/文件上传\x12\x12中止分片上传*\x0eAbortMultipart\x82\xd3\xe4\x93\x02&:\x01**!/v1/system/upload/multipart/abort\x12{\n" +
	"\x05Login\x12\x10.v1.LoginRequest\x1a\x11.v1.LoginResponse\"M\x92A*\n" +
	"\x13system/用户管理\x12\f用户登录*\x05Login\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/system/auth/login\x12\x9f\x01\n" +
	"\fRefreshToken\x12\x17.v1.RefreshTokenRequest\x1a\x18.v1.RefreshTokenResponse\"\\\x92A1\n" +
	"\x13system/用户管理\x12\f刷新令牌*\fRefreshToken\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/v1/system/auth/refresh-token\x12\xb3\x01\n" +
	"\x0eChangePassword\x12\x19.v1.ChangePasswordRequest\x1a\x1a.v1.ChangePasswordResponse\"j\x92A3\n" +
	"\x13system/用户管理\x12\f修改密码*\x0eChangePassword\x82\xd3\xe4\x93\x02.:\x01*\x1a)/v1/system/users/{userID}/change-password\x12\x8a\x01\n" +
	"\n" +
	"CreateUser\x12\x15.v1.CreateUserRequest\x1a\x16.v1.CreateUserResponse\"M\x92A/\n" +
	"\x13system/用户管理\x12\f创建用户*\n" +
	"CreateUser\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/system/users\x12\x99\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.v1.UpdateUserRequest\x1a\x16.v1.UpdateUserResponse\"\\\x92A5\n" +
	"\x13system/用户管理\x12\x12更新用户信息*\n" +
	"UpdateUser\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1/system/users/{userID}\x12\x90\x01\n" +
	"\n" +
	"DeleteUser\x12\x15.v1.DeleteUserRequest\x1a\x16.v1.DeleteUserResponse\"S\x92A/\n" +
	"\x13system/用户管理\x12\f删除用户*\n" +
	"DeleteUser\x82\xd3\xe4\x93\x02\x1b*\x19/v1/system/users/{userID}\x12\x8a\x01\n" +
	"\aGetUser\x12\x12.v1.GetUserRequest\x1a\x13.v1.GetUserResponse\"V\x92A2\n" +
	"\x13system/用户管理\x12\x12获取用户信息*\aGetUser\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/system/users/{userID}\x12\x85\x01\n" +
	"\bListUser\x12\x13.v1.ListUserRequest\x1a\x14.v1.ListUserResponse\"N\x92A3\n" +
	"\x13system/用户管理\x12\x12列出所有用户*\bListUser\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/system/users\x12\x8a\x01\n" +
	"\n" +
	"CreatePost\x12\x15.v1.CreatePostRequest\x1a\x16.v1.CreatePostResponse\"M\x92A/\n" +
	"\x13system/博客管理\x12\f创建文章*\n" +
	"CreatePost\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/system/posts\x12\x93\x01\n" +
	"\n" +
	"UpdatePost\x12\x15.v1.UpdatePostRequest\x1a\x16.v1.UpdatePostResponse\"V\x92A/\n" +
	"\x13system/博客管理\x12\f更新文章*\n" +
	"UpdatePost\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/v1/system/posts/{postID}\x12\x8a\x01\n" +
	"\n" +
	"DeletePost\x12\x15.v1.DeletePostRequest\x1a\x16.v1.DeletePostResponse\"M\x92A/\n" +
	"\x13system/博客管理\x12\f删除文章*\n" +
	"DeletePost\x82\xd3\xe4\x93\x02\x15:\x01**\x10/v1/system/posts\x12\x8a\x01\n" +
	"\aGetPost\x12\x12.v1.GetPostRequest\x1a\x13.v1.GetPostResponse\"V\x92A2\n" +
	"\x13system/博客管理\x12\x12获取文章信息*\aGetPost\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/system/posts/{postID}\x12\x85\x01\n" +
	"\bListPost\x12\x13.v1.ListPostRequest\x1a\x14.v1.ListPostResponse\"N\x92A3\n" +
	"\x13system/博客管理\x12\x12列出所有文章*\bListPost\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/system/posts\x12\x9f\x01\n" +
	"\x0eCreateCategory\x12\x19.v1.CreateCategoryRequest\x1a\x1a.v1.CreateCategoryResponse\"V\x92A3\n" +
	"\x13system/分类管理\x12\f创建分类*\x0eCreateCategory\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/system/categories\x12\xac\x01\n" +
	"\x0eUpdateCategory\x12\x19.v1.UpdateCategoryRequest\x1a\x1a.v1.UpdateCategoryResponse\"c\x92A3\n" +
	"\x13system/分类管理\x12\f更新分类*\x0eUpdateCategory\x82\xd3\xe4\x93\x02':\x01*\x1a\"/v1/system/categories/{categoryID}\x12\xa9\x01\n" +
	"\x0eDeleteCategory\x12\x19.v1.DeleteCategoryRequest\x1a\x1a.v1.DeleteCategoryResponse\"`\x92A3\n" +
	"\x13system/分类管理\x12\f删除分类*\x0eDeleteCategory\x82\xd3\xe4\x93\x02$*\"/v1/system/categories/{categoryID}\x12\xa3\x01\n" +
	"\vGetCategory\x12\x16.v1.GetCategoryRequest\x1a\x17.v1.GetCategoryResponse\"c\x92A6\n" +
	"\x13system/分类管理\x12\x12获取分类信息*\vGetCategory\x82\xd3\xe4\x93\x02$\x12\"/v1/system/categories/{categoryID}\x12\x9a\x01\n" +
	"\fListCategory\x12\x17.v1.ListCategoryRequest\x1a\x18.v1.ListCategoryResponse\"W\x92A7\n" +
	"\x13system/分类管理\x12\x12列出所有分类*\fListCategory\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/system/categories\x12\x85\x01\n" +
	"\tCreateTag\x12\x14.v1.CreateTagRequest\x1a\x15.v1.CreateTagResponse\"K\x92A.\n" +
	"\x13system/标签管理\x12\f创建标签*\tCreateTag\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/system/tags\x12\x8d\x01\n" +
	"\tUpdateTag\x12\x14.v1.UpdateTagRequest\x1a\x15.v1.UpdateTagResponse\"S\x92A.\n" +
	"\x13system/标签管理\x12\f更新标签*\tUpdateTag\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/system/tags/{tagID}\x12\x8a\x01\n" +
	"\tDeleteTag\x12\x14.v1.DeleteTagRequest\x1a\x15.v1.DeleteTagResponse\"P\x92A.\n" +
	"\x13system/标签管理\x12\f删除标签*\tDeleteTag\x82\xd3\xe4\x93\x02\x19*\x17/v1/system/tags/{tagID}\x12\x84\x01\n" +
	"\x06GetTag\x12\x11.v1.GetTagRequest\x1a\x12.v1.GetTagResponse\"S\x92A1\n" +
	"\x13system/标签管理\x12\x12获取标签信息*\x06GetTag\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/system/tags/{tagID}\x12\x80\x01\n" +
	"\aListTag\x12\x12.v1.ListTagRequest\x1a\x13.v1.ListTagResponse\"L\x92A2\n" +
	"\x13system/标签管理\x12\x12列出所有标签*\aListTag\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/system/tags\x12\xac\x01\n" +
	"\rCreatePostTag\x12\x18.v1.CreatePostTagRequest\x1a\x19.v1.CreatePostTagResponse\"f\x92AD\n" +
	"\x19system/文章标签管理\x12\x18创建文章标签关联*\rCreatePostTag\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/system/post-tags\x12\xac\x01\n" +
	"\rDeletePostTag\x12\x18.v1.DeletePostTagRequest\x1a\x19.v1.DeletePostTagResponse\"f\x92AD\n" +
	"\x19system/文章标签管理\x12\x18删除文章标签关联*\rDeletePostTag\x82\xd3\xe4\x93\x02\x19:\x01**\x14/v1/system/post-tags\x12\xa5\x01\n" +
	"\fListPostTags\x12\x17.v1.ListPostTagsRequest\x1a\x18.v1.ListPostTagsResponse\"b\x92AC\n" +
	"\x19system/文章标签管理\x12\x18列出文章标签关联*\fListPostTags\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/system/post-tags\x12\xd0\x01\n" +
	"\x13BatchCreatePostTags\x12\x1e.v1.BatchCreatePostTagsRequest\x1a\x1f.v1.BatchCreatePostTagsResponse\"x\x92AP\n" +
	"\x19system/文章标签管理\x12\x1e批量创建文章标签关联*\x13BatchCreatePostTags\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/system/post-tags/batch\x12\xd0\x01\n" +
	"\x13BatchDeletePostTags\x12\x1e.v1.BatchDeletePostTagsRequest\x1a\x1f.v1.BatchDeletePostTagsResponse\"x\x92AP\n" +
	"\x19system/文章标签管理\x12\x1e批量删除文章标签关联*\x13BatchDeletePostTags\x82\xd3\xe4\x93\x02\x1f:\x01**\x1a/v1/system/post-tags/batch\x12\x7f\n" +
	"\vAppPostList\x12\x13.v1.ListPostRequest\x1a\x14.v1.ListPostResponse\"E\x92A-\n" +
	"\x10app/博客管理\x12\f列出文章*\vAppPostList\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/app/posts\x12\x8a\x01\n" +
	"\n" +
	"AppGetPost\x12\x12.v1.GetPostRequest\x1a\x13.v1.GetPostResponse\"S\x92A2\n" +
	"\x10app/博客管理\x12\x12获取文章信息*\n" +
	"AppGetPost\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/app/posts/{postID}\x12\xa5\x01\n" +
	"\x10BatchAppGetPosts\x12\x18.v1.BatchGetPostsRequest\x1a\x19.v1.BatchGetPostsResponse\"\\\x92A>\n" +
	"\x10app/博客管理\x12\x18批量获取文章信息*\x10BatchAppGetPosts\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/app/posts/batch\x12\xa0\x01\n" +
	"\x0eAppGetCategory\x12\x16.v1.GetCategoryRequest\x1a\x17.v1.GetCategoryResponse\"]\x92A3\n" +
	"\x10app/分类管理\x12\x12获取分类信息*\vGetCategory\x82\xd3\xe4\x93\x02!\x12\x1f/v1/app/categories/{categoryID}\x12\x97\x01\n" +
	"\x0fAppListCategory\x12\x17.v1.ListCategoryRequest\x1a\x18.v1.ListCategoryResponse\"Q\x92A4\n" +
	"\x10app/分类管理\x12\x12列出所有分类*\fListCategory\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/app/categoriesB\xbe\x04\x92A\x82\x04\x12\xd8\x03\n" +
	"\vminiblog v2\x12\x9d\x02MiniBlog 是一个基于 gRPC 的博客系统 API 服务，提供完整的博客管理功能，包括：\n" +
	"- 用户认证与管理\n" +
	"- 博客文章管理\n" +
	"- 分类管理\n" +
	"- 标签管理\n" +
	"- 文章标签关联管理\n" +
	"\n" +
	"采用 RESTful 风格设计，支持通过 HTTP/JSON 访问所有 gRPC 接口\"Y\n" +
	"\x18小而美的博客项目\x12&https://github.com/clin211/miniblog-v2\x1a\x1576742542lin@gmail.com*I\n" +
	"\vMIT License\x12:https://github.com/clin211/miniblog-v2/blob/master/LICENSE2\x031.0*\x01\x022\x10application/json:\x10application/jsonZ6github.com/clin211/miniblog-v2/pkg/api/apiserver/v1;v1b\x06proto3"

var file_apiserver_v1_apiserver_proto_goTypes = []any{
	(*emptypb.Empty)(nil),               // 0: google.protobuf.Empty
	(*UploadFileRequest)(nil),           // 1: v1.UploadFileRequest
	(*InitMultipartRequest)(nil),        // 2: v1.InitMultipartRequest
	(*PresignPartsRequest)(nil),         // 3: v1.PresignPartsRequest
	(*UploadPartRequest)(nil),           // 4: v1.UploadPartRequest
	(*ListPartsRequest)(nil),            // 5: v1.ListPartsRequest
	(*CompleteMultipartRequest)(nil),    // 6: v1.CompleteMultipartRequest
	(*AbortMultipartRequest)(nil),       // 7: v1.AbortMultipartRequest
	(*LoginRequest)(nil),                // 8: v1.LoginRequest
	(*RefreshTokenRequest)(nil),         // 9: v1.RefreshTokenRequest
	(*ChangePasswordRequest)(nil),       // 10: v1.ChangePasswordRequest
	(*CreateUserRequest)(nil),           // 11: v1.CreateUserRequest
	(*UpdateUserRequest)(nil),           // 12: v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),           // 13: v1.DeleteUserRequest
	(*GetUserRequest)(nil),              // 14: v1.GetUserRequest
	(*ListUserRequest)(nil),             // 15: v1.ListUserRequest
	(*CreatePostRequest)(nil),           // 16: v1.CreatePostRequest
	(*UpdatePostRequest)(nil),           // 17: v1.UpdatePostRequest
	(*DeletePostRequest)(nil),           // 18: v1.DeletePostRequest
	(*GetPostRequest)(nil),              // 19: v1.GetPostRequest
	(*ListPostRequest)(nil),             // 20: v1.ListPostRequest
	(*CreateCategoryRequest)(nil),       // 21: v1.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),       // 22: v1.UpdateCategoryRequest
	(*DeleteCategoryRequest)(nil),       // 23: v1.DeleteCategoryRequest
	(*GetCategoryRequest)(nil),          // 24: v1.GetCategoryRequest
	(*ListCategoryRequest)(nil),         // 25: v1.ListCategoryRequest
	(*CreateTagRequest)(nil),            // 26: v1.CreateTagRequest
	(*UpdateTagRequest)(nil),            // 27: v1.UpdateTagRequest
	(*DeleteTagRequest)(nil),            // 28: v1.DeleteTagRequest
	(*GetTagRequest)(nil),               // 29: v1.GetTagRequest
	(*ListTagRequest)(nil),              // 30: v1.ListTagRequest
	(*CreatePostTagRequest)(nil),        // 31: v1.CreatePostTagRequest
	(*DeletePostTagRequest)(nil),        // 32: v1.DeletePostTagRequest
	(*ListPostTagsRequest)(nil),         // 33: v1.ListPostTagsRequest
	(*BatchCreatePostTagsRequest)(nil),  // 34: v1.BatchCreatePostTagsRequest
	(*BatchDeletePostTagsRequest)(nil),  // 35: v1.BatchDeletePostTagsRequest
	(*BatchGetPostsRequest)(nil),        // 36: v1.BatchGetPostsRequest
	(*HealthzResponse)(nil),             // 37: v1.HealthzResponse
	(*UploadedObject)(nil),              // 38: v1.UploadedObject
	(*InitMultipartResponse)(nil),       // 39: v1.InitMultipartResponse
	(*PresignPartsResponse)(nil),        // 40: v1.PresignPartsResponse
	(*UploadPartResponse)(nil),          // 41: v1.UploadPartResponse
	(*ListPartsResponse)(nil),           // 42: v1.ListPartsResponse
	(*CompleteMultipartResponse)(nil),   // 43: v1.CompleteMultipartResponse
	(*AbortMultipartResponse)(nil),      // 44: v1.AbortMultipartResponse
	(*LoginResponse)(nil),               // 45: v1.LoginResponse
	(*RefreshTokenResponse)(nil),        // 46: v1.RefreshTokenResponse
	(*ChangePasswordResponse)(nil),      // 47: v1.ChangePasswordResponse
	(*CreateUserResponse)(nil),          // 48: v1.CreateUserResponse
	(*UpdateUserResponse)(nil),          // 49: v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),          // 50: v1.DeleteUserResponse
	(*GetUserResponse)(nil),             // 51: v1.GetUserResponse
	(*ListUserResponse)(nil),            // 52: v1.ListUserResponse
	(*CreatePostResponse)(nil),          // 53: v1.CreatePostResponse
	(*UpdatePostResponse)(nil),          // 54: v1.UpdatePostResponse
	(*DeletePostResponse)(nil),          // 55: v1.DeletePostResponse
	(*GetPostResponse)(nil),             // 56: v1.GetPostResponse
	(*ListPostResponse)(nil),            // 57: v1.ListPostResponse
	(*CreateCategoryResponse)(nil),      // 58: v1.CreateCategoryResponse
	(*UpdateCategoryResponse)(nil),      // 59: v1.UpdateCategoryResponse
	(*DeleteCategoryResponse)(nil),      // 60: v1.DeleteCategoryResponse
	(*GetCategoryResponse)(nil),         // 61: v1.GetCategoryResponse
	(*ListCategoryResponse)(nil),        // 62: v1.ListCategoryResponse
	(*CreateTagResponse)(nil),           // 63: v1.CreateTagResponse
	(*UpdateTagResponse)(nil),           // 64: v1.UpdateTagResponse
	(*DeleteTagResponse)(nil),           // 65: v1.DeleteTagResponse
	(*GetTagResponse)(nil),              // 66: v1.GetTagResponse
	(*ListTagResponse)(nil),             // 67: v1.ListTagResponse
	(*CreatePostTagResponse)(nil),       // 68: v1.CreatePostTagResponse
	(*DeletePostTagResponse)(nil),       // 69: v1.DeletePostTagResponse
	(*ListPostTagsResponse)(nil),        // 70: v1.ListPostTagsResponse
	(*BatchCreatePostTagsResponse)(nil), // 71: v1.BatchCreatePostTagsResponse
	(*BatchDeletePostTagsResponse)(nil), // 72: v1.BatchDeletePostTagsResponse
	(*BatchGetPostsResponse)(nil),       // 73: v1.BatchGetPostsResponse
}
var file_apiserver_v1_apiserver_proto_depIdxs = []int32{
	0,  // 0: v1.MiniBlog.Healthz:input_type -> google.protobuf.Empty
	1,  // 1: v1.MiniBlog.UploadFile:input_type -> v1.UploadFileRequest
	2,  // 2: v1.MiniBlog.InitMultipart:input_type -> v1.InitMultipartRequest
	3,  // 3: v1.MiniBlog.PresignParts:input_type -> v1.PresignPartsRequest
	4,  // 4: v1.MiniBlog.UploadPart:input_type -> v1.UploadPartRequest
	5,  // 5: v1.MiniBlog.ListParts:input_type -> v1.ListPartsRequest
	6,  // 6: v1.MiniBlog.CompleteMultipart:input_type -> v1.CompleteMultipartRequest
	7,  // 7: v1.MiniBlog.AbortMultipart:input_type -> v1.AbortMultipartRequest
	8,  // 8: v1.MiniBlog.Login:input_type -> v1.LoginRequest
	9,  // 9: v1.MiniBlog.RefreshToken:input_type -> v1.RefreshTokenRequest
	10, // 10: v1.MiniBlog.ChangePassword:input_type -> v1.ChangePasswordRequest
	11, // 11: v1.MiniBlog.CreateUser:input_type -> v1.CreateUserRequest
	12, // 12: v1.MiniBlog.UpdateUser:input_type -> v1.UpdateUserRequest
	13, // 13: v1.MiniBlog.DeleteUser:input_type -> v1.DeleteUserRequest
	14, // 14: v1.MiniBlog.GetUser:input_type -> v1.GetUserRequest
	15, // 15: v1.MiniBlog.ListUser:input_type -> v1.ListUserRequest
	16, // 16: v1.MiniBlog.CreatePost:input_type -> v1.CreatePostRequest
	17, // 17: v1.MiniBlog.UpdatePost:input_type -> v1.UpdatePostRequest
	18, // 18: v1.MiniBlog.DeletePost:input_type -> v1.DeletePostRequest
	19, // 19: v1.MiniBlog.GetPost:input_type -> v1.GetPostRequest
	20, // 20: v1.MiniBlog.ListPost:input_type -> v1.ListPostRequest
	21, // 21: v1.MiniBlog.CreateCategory:input_type -> v1.CreateCategoryRequest
	22, // 22: v1.MiniBlog.UpdateCategory:input_type -> v1.UpdateCategoryRequest
	23, // 23: v1.MiniBlog.DeleteCategory:input_type -> v1.DeleteCategoryRequest
	24, // 24: v1.MiniBlog.GetCategory:input_type -> v1.GetCategoryRequest
	25, // 25: v1.MiniBlog.ListCategory:input_type -> v1.ListCategoryRequest
	26, // 26: v1.MiniBlog.CreateTag:input_type -> v1.CreateTagRequest
	27, // 27: v1.MiniBlog.UpdateTag:input_type -> v1.UpdateTagRequest
	28, // 28: v1.MiniBlog.DeleteTag:input_type -> v1.DeleteTagRequest
	29, // 29: v1.MiniBlog.GetTag:input_type -> v1.GetTagRequest
	30, // 30: v1.MiniBlog.ListTag:input_type -> v1.ListTagRequest
	31, // 31: v1.MiniBlog.CreatePostTag:input_type -> v1.CreatePostTagRequest
	32, // 32: v1.MiniBlog.DeletePostTag:input_type -> v1.DeletePostTagRequest
	33, // 33: v1.MiniBlog.ListPostTags:input_type -> v1.ListPostTagsRequest
	34, // 34: v1.MiniBlog.BatchCreatePostTags:input_type -> v1.BatchCreatePostTagsRequest
	35, // 35: v1.MiniBlog.BatchDeletePostTags:input_type -> v1.BatchDeletePostTagsRequest
	20, // 36: v1.MiniBlog.AppPostList:input_type -> v1.ListPostRequest
	19, // 37: v1.MiniBlog.AppGetPost:input_type -> v1.GetPostRequest
	36, // 38: v1.MiniBlog.BatchAppGetPosts:input_type -> v1.BatchGetPostsRequest
	24, // 39: v1.MiniBlog.AppGetCategory:input_type -> v1.GetCategoryRequest
	25, // 40: v1.MiniBlog.AppListCategory:input_type -> v1.ListCategoryRequest
	37, // 41: v1.MiniBlog.Healthz:output_type -> v1.HealthzResponse
	38, // 42: v1.MiniBlog.UploadFile:output_type -> v1.UploadedObject
	39, // 43: v1.MiniBlog.InitMultipart:output_type -> v1.InitMultipartResponse
	40, // 44: v1.MiniBlog.PresignParts:output_type -> v1.PresignPartsResponse
	41, // 45: v1.MiniBlog.UploadPart:output_type -> v1.UploadPartResponse
	42, // 46: v1.MiniBlog.ListParts:output_type -> v1.ListPartsResponse
	43, // 47: v1.MiniBlog.CompleteMultipart:output_type -> v1.CompleteMultipartResponse
	44, // 48: v1.MiniBlog.AbortMultipart:output_type -> v1.AbortMultipartResponse
	45, // 49: v1.MiniBlog.Login:output_type -> v1.LoginResponse
	46, // 50: v1.MiniBlog.RefreshToken:output_type -> v1.RefreshTokenResponse
	47, // 51: v1.MiniBlog.ChangePassword:output_type -> v1.ChangePasswordResponse
	48, // 52: v1.MiniBlog.CreateUser:output_type -> v1.CreateUserResponse
	49, // 53: v1.MiniBlog.UpdateUser:output_type -> v1.UpdateUserResponse
	50, // 54: v1.MiniBlog.DeleteUser:output_type -> v1.DeleteUserResponse
	51, // 55: v1.MiniBlog.GetUser:output_type -> v1.GetUserResponse
	52, // 56: v1.MiniBlog.ListUser:output_type -> v1.ListUserResponse
	53, // 57: v1.MiniBlog.CreatePost:output_type -> v1.CreatePostResponse
	54, // 58: v1.MiniBlog.UpdatePost:output_type -> v1.UpdatePostResponse
	55, // 59: v1.MiniBlog.DeletePost:output_type -> v1.DeletePostResponse
	56, // 60: v1.MiniBlog.GetPost:output_type -> v1.GetPostResponse
	57, // 61: v1.MiniBlog.ListPost:output_type -> v1.ListPostResponse
	58, // 62: v1.MiniBlog.CreateCategory:output_type -> v1.CreateCategoryResponse
	59, // 63: v1.MiniBlog.UpdateCategory:output_type -> v1.UpdateCategoryResponse
	60, // 64: v1.MiniBlog.DeleteCategory:output_type -> v1.DeleteCategoryResponse
	61, // 65: v1.MiniBlog.GetCategory:output_type -> v1.GetCategoryResponse
	62, // 66: v1.MiniBlog.ListCategory:output_type -> v1.ListCategoryResponse
	63, // 67: v1.MiniBlog.CreateTag:output_type -> v1.CreateTagResponse
	64, // 68: v1.MiniBlog.UpdateTag:output_type -> v1.UpdateTagResponse
	65, // 69: v1.MiniBlog.DeleteTag:output_type -> v1.DeleteTagResponse
	66, // 70: v1.MiniBlog.GetTag:output_type -> v1.GetTagResponse
	67, // 71: v1.MiniBlog.ListTag:output_type -> v1.ListTagResponse
	68, // 72: v1.MiniBlog.CreatePostTag:output_type -> v1.CreatePostTagResponse
	69, // 73: v1.MiniBlog.DeletePostTag:output_type -> v1.DeletePostTagResponse
	70, // 74: v1.MiniBlog.ListPostTags:output_type -> v1.ListPostTagsResponse
	71, // 75: v1.MiniBlog.BatchCreatePostTags:output_type -> v1.BatchCreatePostTagsResponse
	72, // 76: v1.MiniBlog.BatchDeletePostTags:output_type -> v1.BatchDeletePostTagsResponse
	57, // 77: v1.MiniBlog.AppPostList:output_type -> v1.ListPostResponse
	56, // 78: v1.MiniBlog.AppGetPost:output_type -> v1.GetPostResponse
	73, // 79: v1.MiniBlog.BatchAppGetPosts:output_type -> v1.BatchGetPostsResponse
	61, // 80: v1.MiniBlog.AppGetCategory:output_type -> v1.GetCategoryResponse
	62, // 81: v1.MiniBlog.AppListCategory:output_type -> v1.ListCategoryResponse
	41, // [41:82] is the sub-list for method output_type
	0,  // [0:41] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apiserver_v1_apiserver_proto_init() }
func file_apiserver_v1_apiserver_proto_init() {
	if File_apiserver_v1_apiserver_proto != nil {
		return
	}
	file_apiserver_v1_healthz_proto_init()
	file_apiserver_v1_post_proto_init()
	file_apiserver_v1_user_proto_init()
	file_apiserver_v1_category_proto_init()
	file_apiserver_v1_tag_proto_init()
	file_apiserver_v1_post_tag_proto_init()
	file_apiserver_v1_upload_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_apiserver_proto_rawDesc), len(file_apiserver_v1_apiserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiserver_v1_apiserver_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_apiserver_proto_depIdxs,
	}.Build()
	File_apiserver_v1_apiserver_proto = out.File
	file_apiserver_v1_apiserver_proto_goTypes = nil
	file_apiserver_v1_apiserver_proto_depIdxs = nil
}
