// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// PostTag API 定义，包含文章标签关联的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: apiserver/v1/post_tag.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PostTag 表示文章标签关联
type PostTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postID 表示文章 ID
	PostID string `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	// tagID 表示标签 ID
	TagID int32 `protobuf:"varint,2,opt,name=tagID,proto3" json:"tagID,omitempty"`
	// createdAt 表示创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示最后更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTag) Reset() {
	*x = PostTag{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTag) ProtoMessage() {}

func (x *PostTag) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTag.ProtoReflect.Descriptor instead.
func (*PostTag) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{0}
}

func (x *PostTag) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *PostTag) GetTagID() int32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

func (x *PostTag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostTag) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreatePostTagRequest 表示创建文章标签关联请求
type CreatePostTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postID 表示文章 ID
	PostID string `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	// tagID 表示标签 ID
	TagID         int32 `protobuf:"varint,2,opt,name=tagID,proto3" json:"tagID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostTagRequest) Reset() {
	*x = CreatePostTagRequest{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostTagRequest) ProtoMessage() {}

func (x *CreatePostTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostTagRequest.ProtoReflect.Descriptor instead.
func (*CreatePostTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostTagRequest) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *CreatePostTagRequest) GetTagID() int32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

// CreatePostTagResponse 表示创建文章标签关联响应
type CreatePostTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostTagResponse) Reset() {
	*x = CreatePostTagResponse{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostTagResponse) ProtoMessage() {}

func (x *CreatePostTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostTagResponse.ProtoReflect.Descriptor instead.
func (*CreatePostTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{2}
}

// DeletePostTagRequest 表示删除文章标签关联请求
type DeletePostTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postID 表示文章 ID
	PostID string `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	// tagID 表示标签 ID
	TagID         int32 `protobuf:"varint,2,opt,name=tagID,proto3" json:"tagID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostTagRequest) Reset() {
	*x = DeletePostTagRequest{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostTagRequest) ProtoMessage() {}

func (x *DeletePostTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostTagRequest.ProtoReflect.Descriptor instead.
func (*DeletePostTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePostTagRequest) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *DeletePostTagRequest) GetTagID() int32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

// DeletePostTagResponse 表示删除文章标签关联响应
type DeletePostTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostTagResponse) Reset() {
	*x = DeletePostTagResponse{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostTagResponse) ProtoMessage() {}

func (x *DeletePostTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostTagResponse.ProtoReflect.Descriptor instead.
func (*DeletePostTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{4}
}

// ListPostTagsRequest 表示获取文章标签关联列表请求
type ListPostTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postID 表示可选的文章 ID 过滤
	PostID *string `protobuf:"bytes,1,opt,name=postID,proto3,oneof" json:"postID,omitempty"`
	// tagID 表示可选的标签 ID 过滤
	TagID         *int32 `protobuf:"varint,2,opt,name=tagID,proto3,oneof" json:"tagID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostTagsRequest) Reset() {
	*x = ListPostTagsRequest{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostTagsRequest) ProtoMessage() {}

func (x *ListPostTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostTagsRequest.ProtoReflect.Descriptor instead.
func (*ListPostTagsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{5}
}

func (x *ListPostTagsRequest) GetPostID() string {
	if x != nil && x.PostID != nil {
		return *x.PostID
	}
	return ""
}

func (x *ListPostTagsRequest) GetTagID() int32 {
	if x != nil && x.TagID != nil {
		return *x.TagID
	}
	return 0
}

// ListPostTagsResponse 表示获取文章标签关联列表响应
type ListPostTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postTags 表示文章标签关联列表
	PostTags      []*PostTag `protobuf:"bytes,1,rep,name=postTags,proto3" json:"postTags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostTagsResponse) Reset() {
	*x = ListPostTagsResponse{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostTagsResponse) ProtoMessage() {}

func (x *ListPostTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostTagsResponse.ProtoReflect.Descriptor instead.
func (*ListPostTagsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{6}
}

func (x *ListPostTagsResponse) GetPostTags() []*PostTag {
	if x != nil {
		return x.PostTags
	}
	return nil
}

// BatchCreatePostTagsRequest 表示批量创建文章标签关联请求
type BatchCreatePostTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postID 表示文章 ID
	PostID string `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	// tagIDs 表示标签 ID 列表
	TagIDs        []int32 `protobuf:"varint,2,rep,packed,name=tagIDs,proto3" json:"tagIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePostTagsRequest) Reset() {
	*x = BatchCreatePostTagsRequest{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePostTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePostTagsRequest) ProtoMessage() {}

func (x *BatchCreatePostTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePostTagsRequest.ProtoReflect.Descriptor instead.
func (*BatchCreatePostTagsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCreatePostTagsRequest) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *BatchCreatePostTagsRequest) GetTagIDs() []int32 {
	if x != nil {
		return x.TagIDs
	}
	return nil
}

// BatchCreatePostTagsResponse 表示批量创建文章标签关联响应
type BatchCreatePostTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreatePostTagsResponse) Reset() {
	*x = BatchCreatePostTagsResponse{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreatePostTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreatePostTagsResponse) ProtoMessage() {}

func (x *BatchCreatePostTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreatePostTagsResponse.ProtoReflect.Descriptor instead.
func (*BatchCreatePostTagsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{8}
}

// BatchDeletePostTagsRequest 表示批量删除文章标签关联请求
type BatchDeletePostTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// postID 表示文章 ID
	PostID string `protobuf:"bytes,1,opt,name=postID,proto3" json:"postID,omitempty"`
	// tagIDs 表示标签 ID 列表
	TagIDs        []int32 `protobuf:"varint,2,rep,packed,name=tagIDs,proto3" json:"tagIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeletePostTagsRequest) Reset() {
	*x = BatchDeletePostTagsRequest{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeletePostTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeletePostTagsRequest) ProtoMessage() {}

func (x *BatchDeletePostTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeletePostTagsRequest.ProtoReflect.Descriptor instead.
func (*BatchDeletePostTagsRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDeletePostTagsRequest) GetPostID() string {
	if x != nil {
		return x.PostID
	}
	return ""
}

func (x *BatchDeletePostTagsRequest) GetTagIDs() []int32 {
	if x != nil {
		return x.TagIDs
	}
	return nil
}

// BatchDeletePostTagsResponse 表示批量删除文章标签关联响应
type BatchDeletePostTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeletePostTagsResponse) Reset() {
	*x = BatchDeletePostTagsResponse{}
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeletePostTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeletePostTagsResponse) ProtoMessage() {}

func (x *BatchDeletePostTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_post_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeletePostTagsResponse.ProtoReflect.Descriptor instead.
func (*BatchDeletePostTagsResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_post_tag_proto_rawDescGZIP(), []int{10}
}

var File_apiserver_v1_post_tag_proto protoreflect.FileDescriptor

var file_apiserver_v1_post_tag_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x12, 0x38, 0x0a, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x44, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x44, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x61, 0x67, 0x49, 0x44, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x62,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x01, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x44, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x61, 0x67,
	0x49, 0x44, 0x22, 0x3f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74, 0x54,
	0x61, 0x67, 0x73, 0x22, 0x4c, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x67,
	0x49, 0x44, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x67, 0x49, 0x44,
	0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x4c, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x6f, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x6f, 0x73, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x49, 0x44, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x67, 0x49, 0x44, 0x73, 0x22, 0x1d,
	0x0a, 0x1b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x73,
	0x74, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x38, 0x5a,
	0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x6e,
	0x32, 0x31, 0x31, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x62, 0x6c, 0x6f, 0x67, 0x2d, 0x76, 0x32, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiserver_v1_post_tag_proto_rawDescOnce sync.Once
	file_apiserver_v1_post_tag_proto_rawDescData = file_apiserver_v1_post_tag_proto_rawDesc
)

func file_apiserver_v1_post_tag_proto_rawDescGZIP() []byte {
	file_apiserver_v1_post_tag_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_post_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiserver_v1_post_tag_proto_rawDescData)
	})
	return file_apiserver_v1_post_tag_proto_rawDescData
}

var file_apiserver_v1_post_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_post_tag_proto_goTypes = []any{
	(*PostTag)(nil),                     // 0: v1.PostTag
	(*CreatePostTagRequest)(nil),        // 1: v1.CreatePostTagRequest
	(*CreatePostTagResponse)(nil),       // 2: v1.CreatePostTagResponse
	(*DeletePostTagRequest)(nil),        // 3: v1.DeletePostTagRequest
	(*DeletePostTagResponse)(nil),       // 4: v1.DeletePostTagResponse
	(*ListPostTagsRequest)(nil),         // 5: v1.ListPostTagsRequest
	(*ListPostTagsResponse)(nil),        // 6: v1.ListPostTagsResponse
	(*BatchCreatePostTagsRequest)(nil),  // 7: v1.BatchCreatePostTagsRequest
	(*BatchCreatePostTagsResponse)(nil), // 8: v1.BatchCreatePostTagsResponse
	(*BatchDeletePostTagsRequest)(nil),  // 9: v1.BatchDeletePostTagsRequest
	(*BatchDeletePostTagsResponse)(nil), // 10: v1.BatchDeletePostTagsResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_apiserver_v1_post_tag_proto_depIdxs = []int32{
	11, // 0: v1.PostTag.createdAt:type_name -> google.protobuf.Timestamp
	11, // 1: v1.PostTag.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: v1.ListPostTagsResponse.postTags:type_name -> v1.PostTag
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_apiserver_v1_post_tag_proto_init() }
func file_apiserver_v1_post_tag_proto_init() {
	if File_apiserver_v1_post_tag_proto != nil {
		return
	}
	file_apiserver_v1_post_tag_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiserver_v1_post_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_post_tag_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_post_tag_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_post_tag_proto_msgTypes,
	}.Build()
	File_apiserver_v1_post_tag_proto = out.File
	file_apiserver_v1_post_tag_proto_rawDesc = nil
	file_apiserver_v1_post_tag_proto_goTypes = nil
	file_apiserver_v1_post_tag_proto_depIdxs = nil
}
