// Copyright 2025 长林啊 <767425412@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/clin211/miniblog-v2.git.

// Tag API 定义，包含标签的请求和响应消息

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: apiserver/v1/tag.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tag 表示文章标签
type Tag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 表示标签 ID
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// tagID 表示标签 ID
	TagID string `protobuf:"bytes,2,opt,name=tagID,proto3" json:"tagID,omitempty"`
	// name 表示标签名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// color 表示标签颜色(hex 格式)
	Color string `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	// createdAt 表示创建时间（Unix 时间戳）
	CreatedAt int64 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// updatedAt 表示最后更新时间（Unix 时间戳）
	UpdatedAt     int64 `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetTagID() string {
	if x != nil {
		return x.TagID
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Tag) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tag) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CreateTagRequest 表示创建标签请求
type CreateTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 表示标签名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// color 表示标签颜色
	Color         *string `protobuf:"bytes,2,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

// CreateTagResponse 表示创建标签响应
type CreateTagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tagID 表示要获取的标签 tagID
	TagID         string `protobuf:"bytes,1,opt,name=tagID,proto3" json:"tagID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTagResponse) GetTagID() string {
	if x != nil {
		return x.TagID
	}
	return ""
}

// UpdateTagRequest 表示更新标签请求
type UpdateTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tagID 表示要获取的标签 tagID
	// @gotags: uri:"tagID"
	TagID string `protobuf:"bytes,1,opt,name=tagID,proto3" json:"tagID,omitempty" uri:"tagID"`
	// name 表示可选的标签名称
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// color 表示可选的标签颜色
	Color         *string `protobuf:"bytes,3,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTagRequest) GetTagID() string {
	if x != nil {
		return x.TagID
	}
	return ""
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

// UpdateTagResponse 表示更新标签响应
type UpdateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResponse) Reset() {
	*x = UpdateTagResponse{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResponse) ProtoMessage() {}

func (x *UpdateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{4}
}

// DeleteTagRequest 表示删除标签请求
type DeleteTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tagID 表示要获取的标签 tagID
	// @gotags: uri:"tagID"
	TagID         string `protobuf:"bytes,1,opt,name=tagID,proto3" json:"tagID,omitempty" uri:"tagID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTagRequest) GetTagID() string {
	if x != nil {
		return x.TagID
	}
	return ""
}

// DeleteTagResponse 表示删除标签响应
type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{6}
}

// GetTagRequest 表示获取标签请求
type GetTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tagID 表示要获取的标签 tagID
	// @gotags: uri:"tagID"
	TagID         string `protobuf:"bytes,1,opt,name=tagID,proto3" json:"tagID,omitempty" uri:"tagID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagRequest) Reset() {
	*x = GetTagRequest{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRequest) ProtoMessage() {}

func (x *GetTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRequest.ProtoReflect.Descriptor instead.
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{7}
}

func (x *GetTagRequest) GetTagID() string {
	if x != nil {
		return x.TagID
	}
	return ""
}

// GetTagResponse 表示获取标签响应
type GetTagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tag 表示返回的标签信息
	Tag           *Tag `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagResponse) Reset() {
	*x = GetTagResponse{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagResponse) ProtoMessage() {}

func (x *GetTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagResponse.ProtoReflect.Descriptor instead.
func (*GetTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{8}
}

func (x *GetTagResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

// ListTagRequest 表示获取标签列表请求
type ListTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// offset 表示偏移量
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// limit 表示每页数量
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{9}
}

func (x *ListTagRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTagRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListTagResponse 表示获取标签列表响应
type ListTagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tags 表示标签列表
	Tags []*Tag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	// total 表示总数量
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagResponse) Reset() {
	*x = ListTagResponse{}
	mi := &file_apiserver_v1_tag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagResponse) ProtoMessage() {}

func (x *ListTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiserver_v1_tag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagResponse.ProtoReflect.Descriptor instead.
func (*ListTagResponse) Descriptor() ([]byte, []int) {
	return file_apiserver_v1_tag_proto_rawDescGZIP(), []int{10}
}

func (x *ListTagResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_apiserver_v1_tag_proto protoreflect.FileDescriptor

const file_apiserver_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\x16apiserver/v1/tag.proto\x12\x02v1\"\x91\x01\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05tagID\x18\x02 \x01(\tR\x05tagID\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\x03R\tupdatedAt\"K\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05color\x18\x02 \x01(\tH\x00R\x05color\x88\x01\x01B\b\n" +
	"\x06_color\")\n" +
	"\x11CreateTagResponse\x12\x14\n" +
	"\x05tagID\x18\x01 \x01(\tR\x05tagID\"o\n" +
	"\x10UpdateTagRequest\x12\x14\n" +
	"\x05tagID\x18\x01 \x01(\tR\x05tagID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x03 \x01(\tH\x01R\x05color\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_color\"\x13\n" +
	"\x11UpdateTagResponse\"(\n" +
	"\x10DeleteTagRequest\x12\x14\n" +
	"\x05tagID\x18\x01 \x01(\tR\x05tagID\"\x13\n" +
	"\x11DeleteTagResponse\"%\n" +
	"\rGetTagRequest\x12\x14\n" +
	"\x05tagID\x18\x01 \x01(\tR\x05tagID\"+\n" +
	"\x0eGetTagResponse\x12\x19\n" +
	"\x03tag\x18\x01 \x01(\v2\a.v1.TagR\x03tag\">\n" +
	"\x0eListTagRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"D\n" +
	"\x0fListTagResponse\x12\x1b\n" +
	"\x04tags\x18\x01 \x03(\v2\a.v1.TagR\x04tags\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB8Z6github.com/clin211/miniblog-v2/pkg/api/apiserver/v1;v1b\x06proto3"

var (
	file_apiserver_v1_tag_proto_rawDescOnce sync.Once
	file_apiserver_v1_tag_proto_rawDescData []byte
)

func file_apiserver_v1_tag_proto_rawDescGZIP() []byte {
	file_apiserver_v1_tag_proto_rawDescOnce.Do(func() {
		file_apiserver_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiserver_v1_tag_proto_rawDesc), len(file_apiserver_v1_tag_proto_rawDesc)))
	})
	return file_apiserver_v1_tag_proto_rawDescData
}

var file_apiserver_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_apiserver_v1_tag_proto_goTypes = []any{
	(*Tag)(nil),               // 0: v1.Tag
	(*CreateTagRequest)(nil),  // 1: v1.CreateTagRequest
	(*CreateTagResponse)(nil), // 2: v1.CreateTagResponse
	(*UpdateTagRequest)(nil),  // 3: v1.UpdateTagRequest
	(*UpdateTagResponse)(nil), // 4: v1.UpdateTagResponse
	(*DeleteTagRequest)(nil),  // 5: v1.DeleteTagRequest
	(*DeleteTagResponse)(nil), // 6: v1.DeleteTagResponse
	(*GetTagRequest)(nil),     // 7: v1.GetTagRequest
	(*GetTagResponse)(nil),    // 8: v1.GetTagResponse
	(*ListTagRequest)(nil),    // 9: v1.ListTagRequest
	(*ListTagResponse)(nil),   // 10: v1.ListTagResponse
}
var file_apiserver_v1_tag_proto_depIdxs = []int32{
	0, // 0: v1.GetTagResponse.tag:type_name -> v1.Tag
	0, // 1: v1.ListTagResponse.tags:type_name -> v1.Tag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_apiserver_v1_tag_proto_init() }
func file_apiserver_v1_tag_proto_init() {
	if File_apiserver_v1_tag_proto != nil {
		return
	}
	file_apiserver_v1_tag_proto_msgTypes[1].OneofWrappers = []any{}
	file_apiserver_v1_tag_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiserver_v1_tag_proto_rawDesc), len(file_apiserver_v1_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiserver_v1_tag_proto_goTypes,
		DependencyIndexes: file_apiserver_v1_tag_proto_depIdxs,
		MessageInfos:      file_apiserver_v1_tag_proto_msgTypes,
	}.Build()
	File_apiserver_v1_tag_proto = out.File
	file_apiserver_v1_tag_proto_goTypes = nil
	file_apiserver_v1_tag_proto_depIdxs = nil
}
